import Head from "next/head";
import { Layout } from "@/components/layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/1.png";
import { AnimatedText } from "@/components/animated-text";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import { HireMe } from "@/components/hire-me";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Svetlana Levkovskaya</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/3 md:w-[80%] mb-4">
              <Image src={profilePic} alt="image" className="w-full h-auto rounded-l-full lg:hidden md:inline-block
              md:w-full
              "
                     priority
                     sizes="(max-width: 768px) 100vw,
                     (max-width: 1200px) 50vw,
                     50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="Transforming the Vision into Reality through Coding and Design."
                            className="text-6xl text-left
                            x1:!text-6xl lg:!text-5xl lg:!text-center md:!text-4xl sm:!text-3xl xs:!text-2xl
                            " />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled frontend developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link href="/cv.pdf" target={"_blank"}
                      className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                md:p-2 md:px-4 md:text-base
                "
                      download={true}
                >Resume <LinkArrow className="w-6 ml-1" />

                </Link>
                <Link href="mailto:levkovskayase@gmail.com" target={"_blank"}
                      className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="Codebucks" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
